version: "3.1"

services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run start

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      DB_URL: "mongo:27017"
      DB_NAME: "test-db"
    command: python3 main.py

  mongo:
    image: mongo
    restart: always
